### ISSUE TITLE
Automate generation of config.py and poo.ini

### ISSUE THREAD

**Issue by brabo** [phryk/poobrains#12]
Instead of outputing what should go in config.py, a config.py could simply be generated and user made aware of which lines to check. Perhaps same can be done for poo.ini?

**Comment by phryk** [comment]
This has been fixed for a while now.

The `install` command of the CLI has seen quite some work done with config files generated
from jinja templates. This should enable some good flexibility to easily support multiple modes
of deployment in the future.

A `minica` command has been added that creates a minimum viable CA with just the keypair and one certificate.
